### ISSUE TITLE
[Bug Report] Vouchers Can Be Used To Rename Entities

### ISSUE THREAD

**Issue by NotGeri** [badbones69/Vouchers#10]
**Describe the bug**
Vouchers which are set to be `minecraft:name_tag' can be used without activating the voucher on entities renaming the selected entity to the name of the voucher. 

**Versions**
 - Minecraft Server Version: 1.15.2 
 - Plugin Version: 1.8.3

**Pastebin any errors in console**
None.

**Issue**
Vouchers can be used to rename entities and they do not activate meaning there is no way for us to know what happened. Vouchers can be lost accidentally. 

**Screenshots/Videos**
One with and one without vanish.
- https://streamable.com/me1au2
- https://streamable.com/5utqve

**Comment by badbones69** [comment]
This issue was fixed in Vouchers v1.8.4. The commit says armor stands but its meant for all entities.
Commit: a56c5f8f0eee9c51b345506b8b570a38c809d20d
