### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by johnsoncui02** [badbones69/Vouchers#11]
Is this plugin capable of adding a timer and executing multiple commands through using of one?

say i use /customcommand

/customcommand > which executes /event start> then there's a 30 seconds warmup after executes > /event end.

Is this a possibility or maybe a feature that will be added? Thanks!

**Comment by badbones69** [comment]
You could have vouchers try and run a command with this.
https://www.spigotmc.org/resources/delayed-command.44956/
