### ISSUE TITLE
[Bug Report] Can't Turn the Title Off for any Voucher

### ISSUE THREAD

**Issue by FilipeeX** [badbones69/Vouchers#26]
**Description of the Bug**
Every time i try to edit a voucher & disable title, it just wont work. I can click on the green dye that is supposed disable title once clicked, but when i do click it nothing happens, it stays green instead of turning gray indicating that titles are disabled for this voucher.

**Versions:**
 - Minecraft Server Version: Purpur Paper 1446 - 1.18.1 (paperspigot)
 - Plugin Version: 2.1.0

**Console Errors**
There is nothing in console, everything seems to be working fine.

**Screenshots**
There isnt a lot to screenshot here, just a little edit menu, pointing on the dye that's supposed to turn titles off but doesn't.
![This is an image](https://ctrlv.sk/shots/2022/03/28/sbnK.png)

**How to Bypass the Bug**
For now i just set the title of every voucher to &r, that works fine for now..

**Comment by FilipeeX** [comment]
Wasn't expecting a response any time soon.. :/

**Comment by badbones69** [comment]
I believe you are reporting this to the wrong plugin. My 0plugin doesn't have an in-game editor and that version isn't correct.

**Comment by FilipeeX** [comment]
Oh, I didn't realized that. Sorry about that.
