### ISSUE TITLE
Vouchers 1.7.5 doesn’t work with paper mc 70

### ISSUE THREAD

**Issue by Crqnkk** [badbones69/Vouchers#5]
09.06 17:00:36 [Server] INFO [Vouchers] Enabling Vouchers v1.7.5
09.06 17:00:36 [Server] INFO [Vouchers] Loading the Config.yml
09.06 17:00:36 [Server] INFO [Vouchers] Successfully loaded Config.yml
09.06 17:00:36 [Server] INFO [Vouchers] Loading the Data.yml
09.06 17:00:36 [Server] INFO [Vouchers] Successfully loaded Data.yml
09.06 17:00:36 [Server] INFO [Vouchers] Loading the Messages.yml
09.06 17:00:36 [Server] INFO [Vouchers] Successfully loaded Messages.yml
09.06 17:00:36 [Server] INFO [Vouchers] Loading the VoucherCodes.yml
09.06 17:00:36 [Server] INFO [Vouchers] Successfully loaded VoucherCodes.yml
09.06 17:00:36 [Server] ERROR Error occurred while enabling Vouchers v1.7.5 (Is it up to date?)
09.06 17:00:36 [Server] INFO java.lang.NullPointerException: null
09.06 17:00:36 [Server] INFO at me.badbones69.vouchers.api.Vouchers.load(Vouchers.java:24) ~[?:?]
09.06 17:00:36 [Server] INFO at me.badbones69.vouchers.Main.onEnable(Main.java:52) ~[?:?]
09.06 17:00:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.2.jar:git-Paper-70]
09.06 17:00:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
09.06 17:00:36 [Server] INFO [Vouchers] Disabling Vouchers v1.7.5

**Comment by badbones69** [comment]
The newest update should have fixed this issue.
